# Generated by Django 4.2.8 on 2024-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_in_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
