# Generated by Django 4.2.8 on 2024-07-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('remote_token', models.CharField(max_length=50)),
                ('onsite_token', models.CharField(max_length=50)),
            ],
        ),
    ]
